sudo: required
language: java
jdk: openjdk11

services:
  - docker

script:
  # - cd backend
  # - ./mvnw clean install -B
  # - cd ..

after_success:
  # build backend image and push it to hub.docker
  - docker build -t alerougex/awsdemo_backend backend/
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push alerougex/awsdemo_backend


  # # build frontend image and push it to hub.docker
  # - docker build -t alerougex/awsdemo_frontend frontend/
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # - docker push alerougex/_frontend
  # # build nginx image and push it to hub.docker
  # - docker build -t alerougex/awsdemo_nginx nginx/
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # - docker push alerougex/awsdemo_nginx



# deploy:
#   provider: elasticbeanstalk
#   region: eu-central-1
#   app: awsdemo
#   env: awsdemo-env
#   bucket_name: elasticbeanstalk-eu-central-1-398100061250
#   bucket_path: awsdemo
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
