sudo: required
language: java
jdk: openjdk11

services:
  - docker

script:
  - cd backend
  - ./mvnw clean install -B -DskipTests
  - cd ..

# deploy on AWS-ECS -
deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: awsdemo
  env: Awsdemo-env
  bucket_name: elasticbeanstalk-eu-central-1-398100061250
  bucket_path: awsdemo
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
