version: "3.1"

services:

  nginx:
    depends_on:
      - frontend
      - backend
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'

  backend: 
    depends_on: 
      - db
    build: ./backend
    # ports: 
    #   - 8081:8081
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "password"

  frontend:
    depends_on: 
      - backend
    build: ./frontend
    # ports:
    #     - 3000:3000
    
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    volumes:
      - awsdemodb-volume:/var/lib/mysql

volumes:
  awsdemodb-volume:
