version: "3.1"

services:

  nginx:
    depends_on:
      - frontend
      - backend
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'

  backend: 
    depends_on: 
      - db
    build: ./backend
    # ports: 
    #   - 8081:8081
    env_file:
      - ./env/backend.env

  frontend:
    depends_on: 
      - backend
    build: ./frontend
    # ports:
    #     - 3000:3000
    
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    env_file:
      - ./env/db.env
    volumes:
      - awsdemodb-volume:/var/lib/mysql

volumes:
  awsdemodb-volume:
